# Generated by Django 2.2.7 on 2019-11-30 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Tag name')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Post Counts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Post title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('summary', models.CharField(blank=True, default=None, max_length=125, null=True, verbose_name='Post summary')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('trash', 'Trash')], default='draft', max_length=25, verbose_name='Status')),
                ('keywords', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='SEO keywords')),
                ('published', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Published at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tag', models.ManyToManyField(blank=True, related_name='post_tag', to='posts.Tag', verbose_name='Post Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subscribed', models.BooleanField(default=True, verbose_name='Subscribed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_author', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'unique_together': {('email', 'user')},
            },
        ),
    ]
