# Generated by Django 2.2.7 on 2019-11-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featuredimage',
            field=models.ImageField(default=None, null=True, upload_to='featured/%Y/%m/%d', verbose_name='featured image'),
        ),
        migrations.AddField(
            model_name='post',
            name='featuredurl',
            field=models.URLField(default=None, max_length=1024, null=True, verbose_name='featured image url'),
        ),
    ]
