# Generated by Django 2.2.7 on 2019-12-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191130_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featuredimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='featured/%Y/%m/%d', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featuredurl',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='featured image url'),
        ),
    ]
