# Generated by Django 2.2.7 on 2020-01-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191203_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_thumb', models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Default featured thumbnail')),
                ('default_featured', models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Default featured image')),
            ],
            options={
                'verbose_name': 'Post setting',
            },
        ),
    ]
