# Generated by Django 2.2.7 on 2020-01-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featuredthumburl',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='featured thumbnail url'),
        ),
    ]
