# Generated by Django 2.2.7 on 2020-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_featuredthumburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='code',
            field=models.CharField(default=None, max_length=256, unique=True, verbose_name='Unsubsribe code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This User has already subscribed to our updates.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Full name'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
    ]
