# Generated by Django 2.2.7 on 2020-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200108_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Email verified subscriber'),
        ),
    ]
