# Generated by Django 2.2.9 on 2020-01-15 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_subscriber_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featuredimage',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Featured image'),
        ),
    ]
