# Generated by Django 2.2.9 on 2020-01-18 03:40

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200117_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featuredthumb',
            field=posts.models.CloudinaryFieldFix(blank=True, default=None, max_length=255, null=True, verbose_name='featured thumbnail url'),
        ),
    ]
