# Generated by Django 2.2.9 on 2020-01-18 03:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_featuredthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featuredimage',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featuredthumb',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='featured thumbnail url'),
        ),
        migrations.AlterField(
            model_name='postsettings',
            name='default_featured',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Default featured image'),
        ),
        migrations.AlterField(
            model_name='postsettings',
            name='default_thumb',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Default featured thumbnail'),
        ),
    ]
