# Generated by Django 2.2.12 on 2020-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200118_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Post summary'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Tag name'),
        ),
    ]
