# Generated by Django 2.2.7 on 2019-12-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('medium', 'Medium'), ('twitter', 'Twitter'), ('github', 'Github'), ('pintrest', 'Pintrest'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
