# Generated by Django 2.2.7 on 2020-01-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_auto_20191203_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='siteurl',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Website url'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('pintrest', 'Pintrest'), ('medium', 'Medium'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('github', 'Github')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
