# Generated by Django 2.2.7 on 2020-01-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_auto_20200103_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('github', 'Github'), ('pintrest', 'Pintrest'), ('medium', 'Medium'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], default='other', max_length=25, verbose_name='URL Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/%Y/%m/%d', verbose_name='profile image'),
        ),
    ]
