# Generated by Django 2.2.7 on 2020-01-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0004_auto_20200103_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_msg',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Contact Message'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('pintrest', 'Pintrest'), ('github', 'Github'), ('facebook', 'Facebook')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
