# Generated by Django 2.2.7 on 2020-01-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0006_auto_20200103_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='other', max_length=150, verbose_name='Project title')),
                ('thumburl', models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Thumbnail url')),
                ('bloglink', models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Blog URL')),
                ('liveurl', models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Live url')),
            ],
            options={
                'verbose_name': 'Social Url',
                'verbose_name_plural': 'Social Url',
            },
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('github', 'Github'), ('facebook', 'Facebook'), ('pintrest', 'Pintrest'), ('medium', 'Medium')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
