# Generated by Django 2.2.7 on 2020-01-07 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersettings', '0007_auto_20200107_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='defprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_main', to='usersettings.UserProfile', verbose_name='Default Profile'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('pintrest', 'Pintrest'), ('facebook', 'Facebook'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('github', 'Github'), ('linkedin', 'LinkedIn')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
