# Generated by Django 2.2.7 on 2020-01-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0008_auto_20200107_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='codeurl',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Code url'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('pintrest', 'Pintrest'), ('github', 'Github'), ('twitter', 'Twitter'), ('medium', 'Medium'), ('facebook', 'Facebook')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
