# Generated by Django 2.2.7 on 2020-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0010_auto_20200107_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='project/%Y/%m/%d', verbose_name='Project Thumbnail'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('github', 'Github'), ('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('pintrest', 'Pintrest')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
