# Generated by Django 2.2.7 on 2020-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0011_auto_20200107_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('github', 'Github'), ('medium', 'Medium'), ('pintrest', 'Pintrest')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
