# Generated by Django 2.2.7 on 2020-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0012_auto_20200108_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('github', 'Github'), ('medium', 'Medium'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('pintrest', 'Pintrest'), ('twitter', 'Twitter')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
