# Generated by Django 2.2.7 on 2020-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0013_auto_20200108_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='bloglink',
            new_name='blogurl',
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('github', 'Github'), ('twitter', 'Twitter'), ('medium', 'Medium'), ('linkedin', 'LinkedIn'), ('pintrest', 'Pintrest')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
