# Generated by Django 2.2.9 on 2020-01-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0014_auto_20200112_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='details',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Project details'),
        ),
        migrations.AddField(
            model_name='projects',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=125, null=True, verbose_name='Project summary'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('medium', 'Medium'), ('github', 'Github'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('pintrest', 'Pintrest')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
