# Generated by Django 2.2.9 on 2020-01-15 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0015_auto_20200115_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'Github'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('pintrest', 'Pintrest'), ('facebook', 'Facebook')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
