# Generated by Django 2.2.9 on 2020-01-17 06:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0018_auto_20200115_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=posts.models.CloudinaryFieldFix(blank=True, default=None, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='icon',
            field=posts.models.CloudinaryFieldFix(blank=True, default=None, max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('pintrest', 'Pintrest'), ('github', 'Github'), ('facebook', 'Facebook'), ('medium', 'Medium')], default='other', max_length=25, verbose_name='URL Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=posts.models.CloudinaryFieldFix(blank=True, default=None, max_length=255, null=True, verbose_name='Profile picture'),
        ),
    ]
