# Generated by Django 2.2.9 on 2020-01-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0019_auto_20200117_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('github', 'Github'), ('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('pintrest', 'Pintrest')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
