# Generated by Django 2.2.9 on 2020-01-18 03:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0022_auto_20200118_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('medium', 'Medium'), ('linkedin', 'LinkedIn'), ('github', 'Github'), ('twitter', 'Twitter'), ('pintrest', 'Pintrest'), ('facebook', 'Facebook')], default='other', max_length=25, verbose_name='URL Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Profile picture'),
        ),
    ]
