# Generated by Django 2.2.9 on 2020-01-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0023_auto_20200118_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('pintrest', 'Pintrest'), ('facebook', 'Facebook'), ('github', 'Github')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
