# Generated by Django 2.2.12 on 2020-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0025_auto_20200515_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='project_menu_active',
            field=models.BooleanField(default=False, verbose_name='Activate Projects menu'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('medium', 'Medium'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('github', 'Github'), ('pintrest', 'Pintrest')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
