# Generated by Django 2.2.12 on 2020-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0027_auto_20200527_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=270, unique=True),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('pintrest', 'Pintrest'), ('medium', 'Medium'), ('github', 'Github'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], default='other', max_length=25, verbose_name='URL Type'),
        ),
    ]
